# Generated by Django 3.1.5 on 2021-01-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=30)),
                ('Modelo', models.CharField(max_length=180)),
                ('Marca', models.CharField(max_length=150)),
                ('Ano', models.CharField(max_length=4)),
                ('Placa', models.CharField(max_length=30)),
                ('Chassi', models.CharField(max_length=100)),
                ('CLRV', models.CharField(max_length=100)),
            ],
        ),
    ]
