# Generated by Django 3.1.5 on 2021-02-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='indice',
            field=models.IntegerField(),
        ),
    ]
